name: DB Migrate

on:
  workflow_call:
  push:
    # branches:
    #   - main
    #   - develop
    paths:
      - 'src/api/**'
      - '.github/workflows/api-db-migrate.yml'

permissions:
  id-token: write
  deployments: write
  statuses: write
  contents: read

jobs:
  migrate:
    name: DB Migrate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: DB migrate
        run: echo "I am doing a noop migrate"
  