name: Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      deployment:
        description: デプロイ方法の選択
        required: true
        default: 'Full'
        type: choice
        options:
          - Full
          - Web
  push:

permissions:
  id-token: write
  deployments: write
  statuses: write
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
      backend: ${{ steps.changes.outputs.backend }}
    steps:
      - name: Start
        run: echo "Deploy started!"

  # バックエンドをデプロイする場合
  backend-api:
    needs: [changes]
    if: ${{ needs.changes.outputs.backend == 'true' && needs.changes.outputs.frontend == 'true' }}
    uses: ./.github/workflows/api-deploy.yml
  frontend-web:
    needs: [backend-api]
    uses: ./.github/workflows/web-deploy.yml 

  # フロントだけデプロイする場合
  frontend-web-only:
    needs: [changes]
    if: ${{ needs.changes.outputs.backend == 'false' && needs.changes.outputs.frontend == 'true' }}
    uses: ./.github/workflows/web-deploy.yml
