name: Web Deploy

on:
  workflow_call:
  push:
    # branches:
    #   - main
    #   - develop
    paths:
      - 'src/web/**'
      - '.github/workflows/web-deploy.yml'

permissions:
  id-token: write
  deployments: write
  statuses: write
  contents: read

jobs:
  migrate:
    name: Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "I am doing a noop deploy"
  